name: 'diff-dirs-action'
description: 'Generate and post diff in comments on Github Pull Request.'
author: 'Kazys Gurskas'
branding:
  icon: 'git-pull-request'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/kazysgurskas/diff-dirs:latest'
inputs:
  token:
    description: 'GitHub token for posting comments'
    required: true
    default: ${{ github.token }}
  source-dir:
    description: 'Source directory for comparison (typically from head branch)'
    required: true
  target-dir:
    description: 'Target directory for comparison (typically from base branch)'
    required: true
  max-comment-size:
    description: 'Maximum size in characters for each comment'
    required: false
    default: '65000'
  ignore-patterns:
    description: 'Comma-separated list of file patterns to ignore'
    required: false
    default: ''
  delete-previous-comments:
    description: 'Whether to delete previous diff comments'
    required: false
    default: 'true'
  include-headers:
    description: 'Whether to include diff headers in comments'
    required: false
    default: 'false'
